httpd_url: 'http://localhost:8081'
command_prefix: 'hey poppo '
autoinsult_rate: '100'
autoinsult_use: 'false'
pearson_token: iiiijjjjkkkkllll
database_table: userlist
overlord_users:
  - 150525424047357952
token: MjQxOTE3NzU0ODQyNTQ2MTc2.DvFUuw.5veuDMXldn2z-0ywpsC8j-Kux8o
twitch_token: mmmmnnnnoooopppp
cat_api_token: qqqqrrrrssssttttt
dog_api_token: f0d3c2dc-b355-45cf-8eac-c08e36bee827
debug_users:
  -
client_secret: C6jXdAJ7U7LlcsdHRdUNoKUoSh_bE2Xn
database_password: password
client_id: '241917754842546176'
database_username: username
google_token: eeeeffffgggghhhh
httpd_port: '8081'
